version: '3'
services:
  mysql-server:
    image: mysql:8.0
    container_name: mysql-server
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
    ports:
      - "3306:3306"
    networks:
      - mynetwork

  nodejs-app:
    build: .
    container_name: nodejs-app
    ports:
      - "8080:8080"
    depends_on:
      - mysql-server
    networks:
      - mynetwork
    links:
      - mysql-server
    environment:
      MYSQL_HOST: mysql-server
      MYSQL_USER: root
      MYSQL_PASSWORD: my-secret-pw
      MYSQL_DB: mydb

networks:
  mynetwork:
